### ISSUE TITLE
That didn't help

### ISSUE THREAD

**Issue by Xnucky** [tawnix/Gmod-2.0-Internal#3]
OK so I can see in the top left corner of the screen it says ESP and Aimbot, ESP is green Aimbot is grey how in the fuck do I turn the aimbot green??????

**Comment by tawnix** [comment]
I removed that stuff, its an old version. I've uploaded the new version under releases.


ESP is on automatically, Aimbot is the mouse button that you click to make your webpage go forward and backwards a page.
![sdfafdaf](https://user-images.githubusercontent.com/20980231/91866749-75637f00-ec38-11ea-9e0a-b751ae4484a2.jpg)
