### ISSUE TITLE
what the frick?

### ISSUE THREAD

**Issue by Xnucky** [tawnix/Gmod-2.0-Internal#4]
I have never seen those two things on a mouse EVER, is there any other way to activate it?

*sorry if I'm being dumb or annoying*

**Comment by tawnix** [comment]
Bro compile the source, its not difficult. 

Those 2 buttons are actually very common now a days. If you don't like it just change the key binds my dude, its literally in the source code.

**Comment by Xnucky** [comment]
Bro how the fuck do I do that?
